version: 0.0
os: linux

# copy every file in the root of your deployment.zip
files:
  - source: .
    destination: /home/ec2-user/deployment

hooks:
  # unpack & prepare (runs the fetch_and_extract.sh you already have)
  BeforeInstall:
    - location: scripts/fetch_and_extract.sh
      timeout: 300
      runas: ec2-user

  # now start everything in one go
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root