resource "aws_secretsmanager_secret" "ssh_private_key" {
  name        = var.secret_name
  description = "Private SSH key for EC2 (generated by Terraform)"
  tags        = var.tags
}

resource "aws_secretsmanager_secret_version" "ssh_private_key_version" {
  secret_id     = aws_secretsmanager_secret.ssh_private_key.id
  secret_string = var.private_key
}
