FROM python:3.9-slim

WORKDIR /app
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Keep the container running indefinitely
CMD ["tail", "-f", "/dev/null"]
