FROM python:3.9-slim

# Install necessary packages
RUN apt-get update && \
    apt-get install -y tar gzip bash curl unzip less procps && \
    rm -rf /var/lib/apt/lists/*

# Set working directory and copy source code
WORKDIR /app
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Keep the container running indefinitely
CMD ["tail", "-f", "/dev/null"]
