name: Backfill Embeddings

# ── Triggers: nightly 11:00 PM Manila (15:00 UTC) + manual dispatch ─────────────────
on:
  # (1) Nightly schedule at 11:00 PM Manila time = 15:00 UTC
  schedule:
    - cron: '0 15 * * *'
  # (2) Manual dispatch, with optional inputs (year/month/day)
  workflow_dispatch:
    inputs:
      year:
        description: 'YYYY (e.g. 2025). Leave blank to process all nulls.'
        required: false
        default: ''
      month:
        description: 'MM (e.g. 06). Leave blank to process all nulls.'
        required: false
        default: ''
      day:
        description: 'DD (e.g. 01). Leave blank to process all nulls.'
        required: false
        default: ''

jobs:
  backfill_embeddings:
    name: Backfill Embeddings (Manila 11 PM)
    runs-on: ubuntu-latest

    # ── Associate this job with the `main` environment (so its secrets automatically load) ──
    environment: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run embedding backfill script
        env:
          # Manual inputs (if you ran with workflow_dispatch)
          YEAR:                 ${{ github.event.inputs.year }}
          MONTH:                ${{ github.event.inputs.month }}
          DAY:                  ${{ github.event.inputs.day }}

          # Pull Snowflake values from the `main` environment secrets:
          SNOWFLAKE_ACCOUNT:    ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:       ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_TOKEN:      ${{ secrets.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_ROLE:       ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE:  ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE:   ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA:     ${{ secrets.SNOWFLAKE_SCHEMA }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/backfill_embeddings.py
