name: Backfill Embeddings

# ── Triggers: nightly 11:00 PM Manila (15:00 UTC) + manual dispatch ─────────────────
on:
  # (1) Nightly schedule at 11:00 PM Manila time = 15:00 UTC
  schedule:
    - cron: '0 15 * * *'
  # (2) Manual dispatch, with optional inputs (year/month/day)
  workflow_dispatch:
    inputs:
      year:
        description: 'YYYY (e.g. 2025). Leave blank to process all nulls.'
        required: false
        default: ''
      month:
        description: 'MM (e.g. 06). Leave blank to process all nulls.'
        required: false
        default: ''
      day:
        description: 'DD (e.g. 01). Leave blank to process all nulls.'
        required: false
        default: ''

jobs:
  backfill_embeddings:
    name: Backfill Embeddings (Manila 11 PM)
    runs-on: ubuntu-latest

    # ── Associate this job with the `main` environment (so its secrets automatically load) ──
    environment: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run embedding backfill script
        env:
          YEAR:   ${{ github.event.inputs.year }}
          MONTH:  ${{ github.event.inputs.month }}
          DAY:    ${{ github.event.inputs.day }}
        run: |
          python scripts/backfill_embeddings.py
