name: Backfill Embeddings

on:
  schedule:
    - cron: '0 15 * * *'   # 11:00 PM Manila (15:00 UTC)
  workflow_dispatch:
    inputs:
      year:
        description: 'YYYY (e.g. 2025). Leave blank to process all nulls.'
        required: false
        default: ''
      month:
        description: 'MM (e.g. 06). Leave blank to process all nulls.'
        required: false
        default: ''
      day:
        description: 'DD (e.g. 01). Leave blank to process all nulls.'
        required: false
        default: ''

jobs:
  backfill_embeddings:
    name: Backfill Embeddings (Manila 11 PM)
    runs-on: ubuntu-latest

    # Tells GitHub to allow pulling both vars.* and secrets.* from “main”
    environment: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run embedding backfill script
        env:
          # Manual date overrides (blank if none)
          YEAR:                 ${{ github.event.inputs.year }}
          MONTH:                ${{ github.event.inputs.month }}
          DAY:                  ${{ github.event.inputs.day }}

          # Pull Snowflake parameters from environment variables (vars.*)
          SNOWFLAKE_ACCOUNT:    ${{ vars.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:       ${{ vars.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE:       ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE:  ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE:   ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA:     ${{ vars.SNOWFLAKE_SCHEMA }}

          # Pull only truly secret values from secrets.*
          SNOWFLAKE_TOKEN:      ${{ secrets.SNOWFLAKE_TOKEN }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/backfill_embeddings.py
